---
name: build-and-publish

env:
  tarball: willow-application-server-ui.tar.gz

on:
  push:

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch full history to be able to gather changed files in all new commits
          fetch-depth: 0
      - name: npm install
        run: npm install
      - name: build
        run: npm run build
      - name: create tarball
        run: tar cfz ${{ env.tarball }} out/
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.tarball }}
          path: ${{ env.tarball }}
      - name: publish on tag
        if: ${{ github.ref_type == 'tag' }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          artifacts: ${{ env.tarball }}
          prerelease: ${{ contains(github.ref, 'delete') || contains(github.ref, 'pre') || contains(github.ref, 'rc') }}
