---
name: build-and-publish

on:
  pull_request:
  push:
    branch:
      - 'main'
      - 'release/**'
    tags:
      - '*'

jobs:
  build-container:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          # fetch full history to be able to gather changed files in all new commits
          fetch-depth: 0


      - name: extract metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: "ghcr.io/${{ github.repository }}"
          tags: |
            type=ref,event=tag
            type=ref,event=branch

      - name: login to ghcr.io
        uses: docker/login-action@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build Willow Application Server UI in Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          # can't push from PR from forks - but disable now for testing
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
